language: node_js
node_js: node
cache: npm
jobs:
  include:
  - stage: BUILD
    if: tag =~ ^@hbgj\/.*[0-9]
    env: NPM_TAG=$([[ "$TRAVIS_TAG" == *-* ]] && echo "next" || echo "latest")
    script:
    - echo "Releasing $TRAVIS_TAG to npm with tag \"$NPM_TAG\" ..."
    before_deploy:
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > "$HOME/.npmrc"
    - cat $HOME/.npmrc
    - npm config ls
    deploy:
      provider: script
      skip_cleanup: true
      script: lerna publish from-git -y --dist-tag $NPM_TAG
      on:
        tags: true
  - stage: TEST
    script:
      - echo "need test"
    on:
      branch: test
