language: node_js
node_js: node
cache: npm
jobs:
  include:
  - stage: BUILD
    if: tag =~ ^@hbgj\/.*[0-9]
    env: NPM_TAG=$([[ "$TRAVIS_TAG" == @*@*-* ]] && echo "next" || echo "latest")
    before_install:
    - echo "before installaaaaaaaaaaaa"
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > "$HOME/.npmrc"
    - echo "//registry.npm.rsscc.cn/repository/hbgj-npm/:_authToken=$HL_TOKEN" >> "$HOME/.npmrc"
    - echo "//registry.npm.rsscc.cn/repository/hbgj-fe/:_authToken=$HL_TOKEN" >> "$HOME/.npmrc"
    - echo "registry=http://registry.npm.rsscc.cn/repository/hbgj-fe/" > "$HOME/.npmrc"
    - cat $HOME/.npmrc
    before_script:
    - echo 'before scriptaaaaaaaaaaaaaa'
    script:
    - echo "Releasing $TRAVIS_TAG to npm with tag \"$NPM_TAG\" ..."
    before_deploy:
    - npm config ls
    deploy:
      provider: script
      skip_cleanup: true
      script: lerna publish from-git -y --dist-tag $NPM_TAG --registry http://registry.npm.rsscc.cn/repository/hbgj-npm/
      on:
        tags: true
  - stage: TEST
    script:
      - echo "need test"
    on:
      branch: test
